spring:
  application:
    name: eureka-server
    
#server:
#  port: 2001
  
eureka:
  server:
  #自我保护状态，关闭后如果在15分钟内心跳失败几率高于85%，则删除服务注册表中的数据
    enable-self-preservation: false
#  instance:
#    hostname: eureka1
#  client:
  #不向自身注册
#    register-with-eureka: false
#    #不向自身拉取注册信息
#    #最后一次心跳后，间隔多久认为微服务不可用，默认80
#    fetch-registry: false
#    eureka-connection-idle-timeout-seconds: 120

---
server:
  port: 2001

spring:
  profiles: eureka1
  
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka
    
---
server:
  port: 2002
  
spring:
  profiles: eureka2
  
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1.2001/eureka